DISCORD_TOKEN="OTMzNzA2MDMxNTU1NTQ3MTk2.GC510J.fwRjUi_HRxUzWqhUVZEfV3d4Lu9o5Wh5CmPaWc"
MONGODB_CONNECTION_STRING="mongodb+srv://szczurox:lDdqTuOaKV9v17Cq@gusbotcluster.hkaorqi.mongodb.net/test?w=majority"