pub static PERMISSION_BAN: &str = "MODERATION_BAN_MEMBERS";
pub static PERMISSION_KICK: &str = "MODERATION_KICK_MEMBERS";
pub static PERMISSION_WARN: &str = "MODERATION_WARN_MEMBERS";
pub static PERMISSION_SEARCH: &str = "MODERATION_SEARCH_MEMBERS";